const api=window.LAYBOKA_API||'';
const id=localStorage.getItem('lbMerchantId')||'';
const session=localStorage.getItem('lbMerchantSession')||'';
const preview=new URLSearchParams(location.search).get('preview')==='1';
const form=document.getElementById('settingsForm');
const status=document.getElementById('settingsStatus');
const headers=()=>session?{'x-merchant-session':session}:{};
const authFetch=(url,options={})=>fetch(url,{...options,headers:{...headers(),...(options.headers||{})}});
const $=id=>document.getElementById(id);
const text=(id,value)=>{if($(id))$(id).textContent=value??'—'};

$('logoutButton')?.addEventListener('click',()=>{localStorage.removeItem('lbMerchantSession');localStorage.removeItem('lbMerchantId');location.assign('index.html#merchant-login')});
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('.dashboard-tab').forEach(tab=>tab.classList.toggle('active',tab.id===`tab-${button.dataset.tab}`))}));

const setPicture=data=>{const image=$('agentPreview'),remove=$('removeAgentPic');if(data){image.src=data;image.hidden=false;remove.hidden=false}else{image.removeAttribute('src');image.hidden=true;remove.hidden=true}};
$('agentPicUpload')?.addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;if(file.size>1024*1024){status.textContent='Please choose an image smaller than 1 MB.';event.target.value='';return}if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type)){status.textContent='Use a PNG, JPG, WEBP, or GIF image.';event.target.value='';return}const reader=new FileReader();reader.onload=()=>setPicture(reader.result);reader.readAsDataURL(file)});
$('removeAgentPic')?.addEventListener('click',()=>{setPicture('');$('agentPicUpload').value='';if(form?.elements.agentPic)form.elements.agentPic.value=''});

const showTrial=d=>{const banner=$('trialBanner');if(!banner)return;if(d.trialActive&&d.trialEndsAt){const days=Math.max(0,Math.ceil((new Date(d.trialEndsAt)-Date.now())/86400000));banner.textContent=`Premium trial: ${days} day${days===1?'':'s'} remaining · Full access during trial`;}else banner.textContent=d.paid?'Paid plan active':'Trial ended · Upgrade to continue using the AI Sales Executive.'};
const fillMetrics=d=>{const m=d.metrics||{};text('metricConversations',m.conversations);text('metricRecommendations',m.recommendedProducts);text('metricCarts',m.cartRecovery);text('metricConversion',m.conversionRate);text('analyticsConversations',m.conversations);text('analyticsRecommendations',m.recommendedProducts);text('analyticsCarts',m.cartRecovery);text('analyticsConversion',m.conversionRate)};
const loadMetrics=async()=>{try{const r=await authFetch(`${api}/api/dashboard?merchantId=${encodeURIComponent(id)}`);if(r.ok)fillMetrics(await r.json())}catch{}};
const loadSettings=async()=>{if(preview){$('previewNotice')?.removeAttribute('hidden');if($('trialBanner'))$('trialBanner').textContent='Premium trial preview · Full access during trial';return}if(!id||!session){status.textContent='Please log in with your Shopify store URL and merchant email first.';setTimeout(()=>location.assign('index.html#merchant-login'),1200);return}try{const r=await authFetch(`${api}/api/merchant/settings?merchantId=${encodeURIComponent(id)}`);const d=await r.json();if(!r.ok)throw new Error(d.error);Object.entries(d.settings||{}).forEach(([key,value])=>{if(form?.elements[key])form.elements[key].value=value});setPicture(d.settings?.agentPic);showTrial(d);await loadMetrics()}catch(error){status.textContent=error.message}};
form?.addEventListener('submit',async event=>{event.preventDefault();if(preview){status.textContent='Preview mode: changes are not saved.';return}status.textContent='Saving…';const body=Object.fromEntries(new FormData(form));body.merchantId=id;body.agentPic=$('agentPreview')?.hidden?'':$('agentPreview').src;try{const r=await authFetch(`${api}/api/merchant/settings`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);status.textContent='Saved. Your chatbot now uses these settings.'}catch(error){status.textContent=error.message}});

const formatDate=value=>value?new Date(value).toLocaleString():'—';
const showBilling=async()=>{if(preview)return;try{const r=await authFetch(`${api}/api/merchant/billing?merchantId=${encodeURIComponent(id)}`);const d=await r.json();if(!r.ok)throw new Error(d.error);showTrial(d);$('billingTitle').textContent=d.trialActive?'Premium trial':`${d.planName||d.plan} plan active`;$('billingMessage').textContent=d.trialActive?'Your account currently has full trial access. Upgrade whenever you are ready.':d.chatLocked?'Your AI Sales Executive is locked. Upgrade to continue.':`Your subscription is active. Status: ${d.subscriptionStatus||'active'}.`;if(d.chatLocked){$('rechargeButton').hidden=false;$('rechargeButton').onclick=()=>startCheckout('premium')}[['detailPlan',d.planName||d.plan],['detailStatus',d.subscriptionStatus||'—'],['detailEmail',d.email],['detailAmount',d.amount?`$${d.amount} ${d.currency||'USD'} / month`:'—'],['detailPaidAt',formatDate(d.paidAt)],['detailSubscription',d.stripeSubscriptionId]].forEach(([key,value])=>text(key,value));$('billingDetails').hidden=false}catch(error){if($('billingMessage'))$('billingMessage').textContent=error.message}};
const startCheckout=async plan=>{const email=localStorage.getItem('lbLoginEmail')||prompt('Enter your billing email:');if(!email)return;try{const r=await fetch(`${api}/api/checkout`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,email,merchantId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error);location.assign(d.url)}catch(error){$('billingMessage').textContent=error.message}};
$('downloadBilling')?.addEventListener('click',()=>{const lines=['Layboka AI - Billing Details','',`Plan: ${$('detailPlan').textContent}`,`Status: ${$('detailStatus').textContent}`,`Email: ${$('detailEmail').textContent}`,`Amount: ${$('detailAmount').textContent}`,`Paid on: ${$('detailPaidAt').textContent}`,`Subscription: ${$('detailSubscription').textContent}`];const esc=v=>v.replace(/[\\()]/g,c=>'\\'+c).replace(/[^\x20-\x7E]/g,'?');const stream=['BT','/F1 12 Tf','50 760 Td',...lines.map((v,i)=>`${i?'0 -24 Td':''} (${esc(v)}) Tj`),'ET'].join('\n');const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const x=pdf.length;pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(o=>`${String(o).padStart(10,'0')} 00000 n `).join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;const url=URL.createObjectURL(new Blob([pdf],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='layboka-billing-details.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
loadSettings();showBilling();
