const form=document.getElementById('settingsForm');
const id=localStorage.getItem('lbMerchantId');
const status=document.getElementById('settingsStatus');
const api=window.LAYBOKA_API||'';
const billingTitle=document.getElementById('billingTitle');
const billingMessage=document.getElementById('billingMessage');
const rechargeButton=document.getElementById('rechargeButton');
const paymentSuccess=document.getElementById('paymentSuccess');
const billingDetails=document.getElementById('billingDetails');
const formatDate=value=>value?new Date(value).toLocaleString():'—';
const trialBanner=document.getElementById('trialBanner');
const updateTrialCountdown=d=>{if(!trialBanner)return;if(d.trialActive&&d.trialEndsAt){const days=Math.max(0,Math.ceil((new Date(d.trialEndsAt)-Date.now())/86400000));trialBanner.textContent=`Premium trial: ${days} day${days===1?'':'s'} remaining · ${d.usage}/${d.limit} chats used · No charge`;}else trialBanner.textContent=`Trial ended · ${d.usage}/${d.limit} chats used`};
const showRecharge=()=>{rechargeButton.hidden=false;rechargeButton.onclick=()=>startCheckout('premium')};
const setText=(element,value)=>{const node=document.getElementById(element);if(node)node.textContent=value||'—'};
const showBillingDetails=d=>{if(!billingDetails)return;setText('detailPlan',d.planName||d.plan);setText('detailStatus',d.subscriptionStatus||'active');setText('detailEmail',d.email);setText('detailAmount',d.amount?`$${Number(d.amount).toLocaleString()} ${d.currency||'USD'} / month`:'—');setText('detailPaidAt',formatDate(d.paidAt));setText('detailSubscription',d.stripeSubscriptionId);billingDetails.hidden=false};
const downloadBilling=()=>{const details=[['Plan',document.getElementById('detailPlan')?.textContent],['Status',document.getElementById('detailStatus')?.textContent],['Billing email',document.getElementById('detailEmail')?.textContent],['Amount',document.getElementById('detailAmount')?.textContent],['Paid on',document.getElementById('detailPaidAt')?.textContent],['Subscription ID',document.getElementById('detailSubscription')?.textContent]];const escapePdf=value=>String(value||'—').replace(/([\\()])/g,'\\$1').replace(/[^\x20-\x7E]/g,'?');const lines=['Layboka AI - Billing Details','',...details.map(([label,value])=>`${label}: ${value||'—'}`)];const stream=['BT','/F1 12 Tf','50 760 Td',...lines.map((line,index)=>`${index?'0 -24 Td':''} (${escapePdf(line)}) Tj`),'ET'].join('\n');const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((object,index)=>{offsets.push(pdf.length);pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>`${String(offset).padStart(10,'0')} 00000 n `).join('\n')}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;const url=URL.createObjectURL(new Blob([pdf],{type:'application/pdf'}));const link=document.createElement('a');link.href=url;link.download='layboka-billing-details.pdf';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.getElementById('downloadBilling')?.addEventListener('click',downloadBilling);
async function loadBilling(){if(!id)return;try{const r=await fetch(`${api}/api/merchant/billing?merchantId=${encodeURIComponent(id)}`);const d=await r.json();if(!r.ok)throw new Error(d.error);const checkout=new URLSearchParams(location.search).get('checkout');const pending=document.getElementById('paymentPending');if(checkout==='success'&&d.subscriptionStatus&&['active','trialing'].includes(d.subscriptionStatus)){paymentSuccess.hidden=false;if(pending)pending.hidden=true;history.replaceState({},'',`${location.pathname}?merchantId=${encodeURIComponent(id)}`)}else if(checkout==='success'&&pending){pending.hidden=false}updateTrialCountdown(d);if(d.trialActive&&!d.chatLocked){billingTitle.textContent='Trial Premium plan';billingMessage.textContent=`You have full Premium features for 5 days with 100 AI chats. Usage: ${d.usage}/${d.limit}. Trial ends ${formatDate(d.trialEndsAt)}. No charge during the trial.`}else if(d.trialActive&&d.chatLocked){billingTitle.textContent='Trial chat limit reached — chatbot locked';billingMessage.textContent=`Your 5-day Premium trial includes ${d.limit} chats and has been used. Recharge Now to continue.`;showRecharge()}else if(d.chatLocked){billingTitle.textContent='Trial ended — chatbot locked';billingMessage.textContent=`Your Premium trial chat limit of ${d.limit} has been reached or your trial has ended. Recharge Now to continue.`;showRecharge()}else{billingTitle.textContent=`${d.planName||d.plan} plan active`;billingMessage.textContent=`Chat limit: ${d.usage}/${d.limit} conversations. Paid amount: $${d.amount||'—'} USD. Status: ${d.subscriptionStatus||'active'}.`;showBillingDetails(d)}}catch(error){billingMessage.textContent=error.message}}
async function startCheckout(plan){const email=prompt('Enter your billing email:');if(!email)return;rechargeButton.disabled=true;try{const r=await fetch(`${api}/api/checkout`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,email,merchantId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error);window.location.href=d.url}catch(error){billingMessage.textContent=error.message;rechargeButton.disabled=false}}
async function load(){if(!id){status.textContent='Complete installation first to customize your executive.';return}try{const r=await fetch(`${api}/api/merchant/settings?merchantId=${encodeURIComponent(id)}`);const d=await r.json();if(r.ok)Object.entries(d.settings).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value})}catch{status.textContent='Unable to load settings.'}}
form?.addEventListener('submit',async e=>{e.preventDefault();if(!id)return;status.textContent='Saving…';const body=Object.fromEntries(new FormData(form));body.merchantId=id;try{const r=await fetch(`${api}/api/merchant/settings`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);status.textContent='Saved. Your chatbot now uses these settings.'}catch(error){status.textContent=error.message}});
loadBilling();load();
